###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

#routes:
#  /blog/archives/*:
#   template: archives
